---
name: PR

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  lint-build-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Setup mise
        uses: jdx/mise-action@v3
        with:
          install: false
          working_directory: /
          env: false
      - name: Install base dependencies
        run: |
          mise --no-config use -g node@24.12.0
          mise --no-config use -g pnpm@10.26.2
          mise --no-config use -g uv@0.9.18
          mise --no-config use -g jq@latest
          mise install
      - name: Configure git
        run: |
          git config --global --add safe.directory '*'
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git config --global user.name "${{ github.actor }}"
      - name: Lint
        run: |
          just lint
      - name: Build
        run: |
          just build
      - name: Test
        run: |
          just test
      - name: Run security scan
        run: |
          just security-scan
